application: kompetencyjny
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /(.*\.css)
  static_files: web/dist/\1
  upload: web/dist(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: web/dist/\1
  upload: web/dist/js/(.*\.js)

- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: web/dist/\1
  upload: web/dist/images(.*\.(gif|jpeg|jpg|png))

- url: /api/.*
<<<<<<< HEAD
  script: main.app
=======
  script: index.html

- url: /(.*\.web)
  static_dir: web

- url: /
  static_files: web/dist/index.html
  upload: web/dist/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: web/\1
  upload: web/(.*\.html)
  expiration: "1h"
>>>>>>> 7a5ccc020eeae05f8c213167efb4151d9fc89cad

- url: /.*
  script: main.app
#- url: /.*
#  static_files: web/dist/index.html
#  upload: web/dist/index.html

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: "1.2"
