application: kompetencyjny
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /(.*\.css)
  static_files: web/dist/\1
  upload: web/dist(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: web/dist/\1
  upload: web/dist/js/(.*\.js)

- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: web/dist/\1
  upload: web/dist/images(.*\.(gif|jpeg|jpg|png))

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: "1.2"
