application: kompetencyjny
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /(.*\.json)
  static_files: web/\1
  upload: web/(.*\.json)

- url: /(.*\.css)
  static_files: web/\1
  upload: web/(.*\.css)

- url: /(.*\.js)
  static_files: web/\1
  upload: web/(.*\.js)


  # image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: web/\1
  upload: web/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /api/.*
  script: project.backend.api.application


- url: /(.*\.coffee)
  static_dir: static/coffee.*

- url: /(.*\.web)
  static_dir: web

- url: /images/
  static_files: static/images/\1
  upload: static/images/

- url: /index\.html
  script: main.app

#/C:\Users\Daniel\bombermanKompetencyjny\web\dist\index.html


- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

