application: kompetencyjny
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /(.*\.css)
  static_files: web/\1
  upload: web/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.*\.js)

- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: web/\1
  upload: web/(.*\.(gif|jpeg|jpg|png))

- url: /api/.*
  script: index.html

- url: /(.*\.web)
  static_dir: web

- url: /
  static_files: web/dist/index.html
  upload: web/dist/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: web/\1
  upload: web/(.*\.html)
  expiration: "1h"

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

